### ISSUE TITLE
Contact Us - When entering "." into any of the fields, the frontend crashes

### ISSUE THREAD

**Issue by matthewjflee** [Vezorla/vezorla-frontend#57]
When entering into any of the fields, the frontend crashes. Most likely has to do with the regex being used onChange method.

![image](https://user-images.githubusercontent.com/15060093/77079335-79b71b00-69bd-11ea-99d2-7e4184c5a744.PNG)

---
Original issue opened by @Kwistech at https://github.com/Vezorla/vezorla-backend/pull/57#issuecomment-601217096

**Comment by S0lRaK** [comment]
Removed _Client_ label, as this bug has nothing to do with having an account, so _Customer_ related (which includes Client).

**Comment by S0lRaK** [comment]
This [commit](https://github.com/Vezorla/vezorla-frontend/commit/ad8534e8b768ce24f5a87a2a2057140c0fd12058) has fixed it.
